spring:
  profiles:
    active: development
---

spring:
  profiles: development
---

spring:
  profiles: production
---

server:
    port: ${PORT:8761}

eureka:
    instance:
        hostname: localhost
    client:
        registerWithEureka: false
        fetchRegistry: false
    server:
        enableSelfPreservation: false