spring:
  profiles:
    active: development
---

spring:
  profiles: development
---

spring:
  profiles: production
---

spring:
  application:
    name: google-drive-search-service

server:
  port: ${PORT:2301}

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

  ribbon:
    eureka:
      enabled: true
